// src/components/Item.vue
<template lang="pug">
.item
  .item__thumbnail
    .item__icon
    .item__tag
  ul.item__meta
    li.item__title
    li.item__creator
      small.item__author
      small.item__duration
</template>
//- syntax highlight fixer comment
<script>
export default {
  name: 'item',
}
</script>
<style lang="scss"></style>

// app/src/components/Item.jsx
import React, {Component} from 'react';

export default class List extends Component {
  render() {
    return (
      <div className="item">
        <div className="item__thumbnail">
          <div className="item__icon"/>
          <div className="item__tag"/>
        </div>
        <ul className="item__meta">
          <li className="item__title"/>
          <li className="item__creator">
            <small className="item__author"/>
            <small className="item__duration"/>
          </li>
        </ul>
      </div>
    );
  }
}
