// app/src/components/NavRight.jsx
import React, {Component} from 'react';

export default class NavRight extends Component {
  render() {
    return (
      <nav id="nav-right" className="nav">
        <button id="toggleYoutube" className="btn btn--nav btn--solo-icon center block">
          <i className="icon material-icons">subscriptions</i>
        </button>
        <button id="toggleSettings" className="btn btn--nav btn--solo-icon center block">
          <i className="icon material-icons">settings</i>
        </button>
        <button id="toggleMute" className="btn btn--nav btn--solo-icon center block">
          <i className="icon material-icons">volume_up</i>
        </button>
        <button id="addToPlaylist" className="btn btn--nav btn--solo-icon center block">
          <i className="icon material-icons">playlist_add</i>
        </button>
        <button id="toggleRepeat" className="btn btn--nav btn--solo-icon center block">
          <i className="icon material-icons">repeat</i>
        </button>
        <button id="toggleShuffle" className="btn btn--nav btn--solo-icon center block">
          <i className="icon material-icons">shuffle</i>
        </button>
        <button id="toggleGrid" className="btn btn--nav btn--solo-icon center block">
          <i className="icon material-icons">view_headline</i>
        </button>
        <button id="replay" className="btn btn--nav btn--solo-icon center block">
          <i className="icon material-icons">autorenew</i>
        </button>
        <button id="addToFavorites" className="btn btn--nav btn--solo-icon center block">
          <i className="icon material-icons">favorite_border</i>
        </button>
      </nav>
    );
  }
}

// src/components/NavRight.vue
<template lang="pug">
nav(id="nav-right" class="nav")
    button(id="toggleYoutube" class="btn btn--nav btn--solo-icon center block" disabled)
        i(class="icon material-icons") subscriptions
    button(id="toggleSettings" class="btn btn--nav btn--solo-icon center block" disabled)
        i(class="icon material-icons") settings
    button(id="toggleMute" class="btn btn--nav btn--solo-icon center block")
        i(class="icon material-icons") volume_up
    button(id="addToPlaylist" class="btn btn--nav btn--solo-icon center block" disabled)
        i(class="icon material-icons") playlist_add
    button(id="toggleRepeat" class="btn btn--nav btn--solo-icon center block")
        i(class="icon material-icons") repeat
    button(id="toggleShuffle" class="btn btn--nav btn--solo-icon center block")
        i(class="icon material-icons") shuffle
    button(id="toggleGrid" class="btn btn--nav btn--solo-icon center block")
        i(class="icon material-icons") view_headline
    button(id="replay" class="btn btn--nav btn--solo-icon center block" data-stateless)
        i(class="icon material-icons") autorenew
    button(id="toggleLargePlayer" class="btn btn--nav btn--solo-icon center block" disabled)
        i(class="icon material-icons") view_carousel
    button(id="addToFavorites" class="btn btn--nav btn--solo-icon center block" disabled)
        i(class="icon material-icons") favorite_border
</template>
